modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="secrets_of_forging_revelations"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.secrets_of_forging_revelations]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.secrets_of_forging_revelations]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.secrets_of_forging_revelations]]
    modId="tetra"
    mandatory=true
    versionRange="${tetra_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.secrets_of_forging_revelations]]
    modId="mutil"
    mandatory=true
    versionRange="${mutil_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.secrets_of_forging_revelations]]
    modId="art_of_forging"
    mandatory=false
    versionRange="${art_of_forging_version_range}"
    ordering="NONE"
    side="BOTH"
